### ISSUE TITLE
Cannot create MongoClient

### ISSUE THREAD

**Issue by MatteoT9890** [mongodb-js/mongodb-connection-string-url#10]
Hi, I'm using typescript with:
- mongodb: ^4.2.0
- mongodb-connection-string-url: 2.2.0

when I create a new MongoClient I encounter this error:

```
     TypeError: Cannot read property 'constructor' of undefined
      at new ConnectionString (node_modules/mongodb-connection-string-url/src/index.ts:149:94)
      at parseOptions (node_modules/mongodb/src/connection_string.ts:253:15)
      at new MongoClient (node_modules/mongodb/src/mongo_client.ts:337:34)
      at Function.connect (node_modules/mongodb/src/mongo_client.ts:517:27)
      at Object.<anonymous> (src/interface/common/Storage/Mongo.ts:13:46)
      at Generator.next (<anonymous>)
      at /home/matt/algor/git-repo/prova-typescript/src/interface/common/Storage/Mongo.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (src/interface/common/Storage/Mongo.ts:4:12)
      at Object.init (src/interface/common/Storage/Mongo.ts:22:16)
      at /home/matt/algor/git-repo/prova-typescript/test/interface/common/Storage/Mongo.test.ts:32:32
      at Generator.next (<anonymous>)
      at /home/matt/algor/git-repo/prova-typescript/test/interface/common/Storage/Mongo.test.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test/interface/common/Storage/Mongo.test.ts:4:12)
      at Context.<anonymous> (test/interface/common/Storage/Mongo.test.ts:28:81)
      at processImmediate (internal/timers.js:461:21)
```

This error seems to be caused by this line of code: 
https://github.com/mongodb-js/mongodb-connection-string-url/blob/main/src/index.ts#L149

**Comment by addaleax** [comment]
Hi @MatteoT9890! That’s very surprising. Do you have any kind of reproduction available? Are you using this in Node.js? What are your typescript options?

**Comment by MatteoT9890** [comment]
Hi @addaleax, I'm using:

- **Node version**: 12.22.1
- This is my `tsconfig.json` file:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "*",
                "node_modules/*",
            ]
        }
    },
    "include": [
        "src/**/*",
        "test/**/*",
        "secrets/**/*",
        "conf/**/*",
        "environment/**/*"
    ]
}
```

- This is the piece of code incriminated:
```
import { MongoClient } from "mongodb";
...
let mongoClient = new MongoClient(MongoDBSecrets.stringConnection)
...
```

Where `MongoDBSecrets.stringConnection` is a valid `+srv` url and, as you can see, default `MongoClientOptions` are used.

Do you have any idea what the source of the error might be? Due to this error I can no longer connect to the database

**Comment by addaleax** [comment]
Hi @MatteoT9890 – I followed all steps you described here and could not reproduce this error, using your exact versions and typescript config: https://github.com/addaleax/mongodb-connection-string-url-10-nonrepro

**Comment by MatteoT9890** [comment]
Hi @addaleax,

previously the error occurred only and exclusively when the creation of the client took place within a mocha test.
Now, with version 4.3, the problem no longer occurs even within the test.
Thank you all the same!

**Comment by victorkwok97** [comment]
I experience the exact same error with the following dependencies
- mongodb: ^4.3.1
- mongodb-connection-string-url: 2.5.2

This is my tsconfig
`{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "types": [
      "nuxt-windicss"
    ],
    "baseUrl": ".",
    "paths": {
      "~/*": ["*"],
      "#app": [
        "./node_modules/nuxt3/dist/app"
      ],
      "#head": [
        "./node_modules/nuxt3/dist/head/runtime"
      ]
    },
  }
}
`

This code leads to the error
`client = await MongoClient.connect(useRuntimeConfig().MONGO_SRV, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        } as MongoClientOptions);`

This is inside a nuxt3 project. Strange thing is that it only occurs when deployed on Netlify but does not occur when run locally.

**Comment by alexCatena** [comment]
@victorkwok97 Did you manage to find a fix for this? I am having the same issue on AWS lambda

**Comment by victorkwok97** [comment]
@alexCatena I upgraded to mongodb version 4.4.1 and then the problem no longer exists.

**Comment by adicco** [comment]
Hello @addaleax I am also encountering this error when running a Dockerized Next.js app with mongoose being used on API routes.

```
TypeError: Cannot read properties of undefined (reading 'constructor')
    at new ConnectionString (/app/node_modules/mongodb-connection-string-url/lib/index.js:153:90)
    at parseOptions (/app/node_modules/mongodb/lib/connection_string.js:209:17)
    at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:65:63)
    at /app/node_modules/mongoose/lib/connection.js:801:16
    at new Promise (<anonymous>)
    at Connection.openUri (/app/node_modules/mongoose/lib/connection.js:798:19)
    at /app/node_modules/mongoose/lib/index.js:381:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
```

This is the offending line:

```ts
Object.setPrototypeOf(this.searchParams, caseInsenstiveURLSearchParams(this.searchParams.constructor).prototype);
```

Interestingly if I put a `console.log(this)` just above, I get:

```
RangeError: Maximum call stack size exceeded
    at [Symbol.hasInstance] (<anonymous>)
    at Object.is (/app/node_modules/whatwg-url/lib/URL.js:176:31)
    at URL.toString (/app/node_modules/whatwg-url/lib/URL.js:51:32)
    at ConnectionString.toString (/app/node_modules/mongodb-connection-string-url/lib/index.js:174:22)
    at get href [as href] (/app/node_modules/mongodb-connection-string-url/lib/index.js:162:30)
    at URL.toString (/app/node_modules/whatwg-url/lib/URL.js:54:15)
    at ConnectionString.toString (/app/node_modules/mongodb-connection-string-url/lib/index.js:174:22)
    at get href [as href] (/app/node_modules/mongodb-connection-string-url/lib/index.js:162:30)
    at URL.toString (/app/node_modules/whatwg-url/lib/URL.js:54:15)
    at ConnectionString.toString (/app/node_modules/mongodb-connection-string-url/lib/index.js:174:22
```

Could that be related to TypeScript compilation? Any help would be greatly appreciated.

**Comment by addaleax** [comment]
@adicco Can you share which exact versions the `whatwg-url` and `mongodb-connection-string-url` packages have in your `node_modules` directory?

**Comment by addaleax** [comment]
@adicco Is there some way that you could try out https://github.com/mongodb-js/mongodb-connection-string-url/pull/24 (e.g. by making npm use a git dependency)? It would fix this issue based on the stack trace you provided above, but I’m a bit hesitant to apply a fix based on a very partial understanding of the problem without actually verifying that it works.

**Comment by adicco** [comment]
@addaleax That fixed the stringification issue; this is what my object looks like:

```
{
  href: 'mongodb://172.17.0.1:27018/kathina-list',
  origin: 'null',
  protocol: 'mongodb:',
  username: '',
  password: '',
  hosts: [ '172.17.0.1:27018' ],
  pathname: '/kathina-list',
  search: '',
  searchParams: undefined,
  hash: ''
}
```

**Comment by adicco** [comment]
Turns out that I was doing some particular build in my Dockerfile because I have another kind of microservice running in parallel, and there seems to be some conflicts between the node_modules. I am satisfied that this is due to my peculiar environment rather than anything wrong with the library itself

**Comment by addaleax** [comment]
@adicco You don’t happen to know more about what kind of conflict that was, do you? It might be nice to know since there have been other people reporting issues on this thread, but all without reproductions … :/

**Comment by adicco** [comment]
Basically, I use the standard [Dockerfile recommended by next.js](https://github.com/vercel/next.js/tree/canary/examples/with-docker) which has several steps in it: dependencies, builder and runner.

In my final container, the runner, I was doing that kind of trickery:

```
WORKDIR /install_bullmq

RUN npm init -y
RUN npm i bullmq ioredis dotenv readline googleapis eventemitter2 luxon

RUN cp -R /install_bullmq/node_modules /app
```

This is because in addition to running next's server.js, I had a microservice running in parallel (using `concurrently`) and for some reason I thought its dependencies (bullmq etc) were not properly installed during the build phase. Apparently, doing that extra, custom npm install and then copying these modules to the main node_modules folder raised the issue I flagged above. As soon as I removed this custom npm install it worked again.

Not sure this is super helpful but if people are doing some kind of wizardry with Dockerfiles this could result in having all sorts of weird errors

**Comment by addaleax** [comment]
Yeah, that would install an older version of whatwg-url over the more recent version. I don’t think that’s something that this package should need to handle.

If this is something that’s recommended publicly in a Dockerfile template somewhere, I’m happy to try to talk to the maintainers to see if this can be fixed.

**Comment by adicco** [comment]
Agree. As far as the Dockerfile template, it doesn't include the kind of shenanigans I did so you can probably save yourself the effort! Many thanks for your help with this :)
